/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recibidores;

import Entidad.EntidadDetalleLote;
import Entidad.EntidadNave;
import Entidad.EntidadOv;
import Entidad.EntidadRecibidor;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionBD;
import modelo.ModeloEncabDetalle;
import modelo.ModeloEncabezado;
import modelo.ModeloNave;
import modelo.ModeloOv;
import modelo.ModeloRecibidor;
import template.MiModelo;

/**
 *
 * @author hgonzalez
 */
public class Liquidaciones extends javax.swing.JFrame {

    /**
     * Creates new form Liqui
     */
    String CodigoTemporada;
    public Liquidaciones(String CodigoTemporada) {
        
            //INICIO CAMBIA A WINDOWS
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //FIN CAMBIA A WINDOWS    
        
        
        initComponents();
            cmbRecibidor.removeAllItems();
            cmbNave.removeAllItems();
            
            lblTemporada.setText(CodigoTemporada);
            ModeloRecibidor MR = new ModeloRecibidor();
            MR.mostrarRecibidor(cmbRecibidor, this.lblTemporada.getText()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDesTemporada = new javax.swing.JLabel();
        lblRecibir = new javax.swing.JLabel();
        cmbRecibidor = new javax.swing.JComboBox<>();
        lblNave = new javax.swing.JLabel();
        cmbNave = new javax.swing.JComboBox<>();
        lblNumeroViaje = new javax.swing.JLabel();
        txtViaje = new javax.swing.JTextField();
        lblOv = new javax.swing.JLabel();
        cmbOv = new javax.swing.JComboBox<>();
        lblGastosrecibidor = new javax.swing.JLabel();
        lblTemporada = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDesTemporada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDesTemporada.setText("Temporada");

        lblRecibir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRecibir.setText("Recibidor");

        cmbRecibidor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbRecibidor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRecibidorItemStateChanged(evt);
            }
        });
        cmbRecibidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRecibidorActionPerformed(evt);
            }
        });

        lblNave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNave.setText("Nave");

        cmbNave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbNave.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNaveItemStateChanged(evt);
            }
        });
        cmbNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNaveActionPerformed(evt);
            }
        });

        lblNumeroViaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumeroViaje.setText("Viaje");

        txtViaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtViaje.setEnabled(false);
        txtViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViajeActionPerformed(evt);
            }
        });

        lblOv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOv.setText("OV");

        cmbOv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbOv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOvItemStateChanged(evt);
            }
        });

        lblGastosrecibidor.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblGastosrecibidor.setText("Liquidaciones");

        lblTemporada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDesTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lblTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecibir)
                            .addComponent(cmbRecibidor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNave)
                            .addComponent(cmbNave, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroViaje))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbOv, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOv)))
                    .addComponent(lblGastosrecibidor))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesTemporada)
                            .addComponent(lblTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRecibir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbRecibidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblOv)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbOv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblNumeroViaje)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lblGastosrecibidor)
                .addContainerGap())
        );

        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLotesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLotes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRecibidorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRecibidorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            cmbNave.removeAllItems();

            EntidadRecibidor Recibidor = (EntidadRecibidor) cmbRecibidor.getSelectedItem();

                        ModeloNave MN = new ModeloNave();
                        MN.mostrarNave(cmbNave, this.lblTemporada.getText(), Recibidor.getCodigorec());

            if (Recibidor.getTemporada()!= ""){
                //CARGAR TABLA
                try{
                        DefaultTableModel modelo = new DefaultTableModel();
                        tblLotes.setModel(modelo);

                        ConexionBD cnn = new ConexionBD();
                        cnn.conectar();
                        ResultSet rs = cnn.consulta("SELECT LLLIQU, LLDENC FROM UNIDATOS.BLIQREL1 "
                                + "WHERE LLCTEM='"+this.lblTemporada.getText()+"'"+" AND LLAARE='"+Recibidor.getCodigorec()+"'"+" ORDER BY LLLIQU, LLDENC");
                        ResultSetMetaData rsMd = rs.getMetaData();
                        int cantidadColumnas = rsMd.getColumnCount();
                        //System.out.println("Resultado RS : " + cantidadColumnas);
                        modelo.addColumn("Liquidacion");
                        modelo.addColumn("Lote");

                        while(rs.next()){
                            Object[] filas = new Object[cantidadColumnas];
                            for(int i = 0; i< cantidadColumnas; i++){
                                filas[i] = rs.getObject(i + 1);                                  
                            }                       
                            modelo.addRow(filas);
                        }    
                    } catch(SQLException ex){

                    }
                //CARGAR TABLA
            }   
        }
    }//GEN-LAST:event_cmbRecibidorItemStateChanged

    private void cmbRecibidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRecibidorActionPerformed

        
    }//GEN-LAST:event_cmbRecibidorActionPerformed

    private void cmbNaveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNaveItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            cmbOv.removeAllItems();
            
            EntidadNave Nave = (EntidadNave) cmbNave.getSelectedItem();
            txtViaje.setText(String.valueOf(Nave.getViaje()));
            
            EntidadRecibidor Recibidor = (EntidadRecibidor) cmbRecibidor.getSelectedItem();
            ModeloOv MO = new ModeloOv();
            MO.mostrarOv(cmbOv, this.lblTemporada.getText(), Recibidor.getCodigorec(), Nave.getCorrelativo());
        }
    }//GEN-LAST:event_cmbNaveItemStateChanged

    private void cmbNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNaveActionPerformed

    private void txtViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViajeActionPerformed

    private void cmbOvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOvItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOvItemStateChanged

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        EntidadRecibidor Recibidor = (EntidadRecibidor) cmbRecibidor.getSelectedItem();
        ArrayList<EntidadDetalleLote> detalle=null;
        //PRUEBA DE LLAMADA A MODELO ENCABEZADO DETALLE
            int Liquidac = 32;
            ModeloEncabDetalle MED = new ModeloEncabDetalle();
        try {
            MED.consultarEncabDetalle(this.lblTemporada.getText(), Recibidor.getCodigorec(), Liquidac);
        } catch (SQLException ex) {
            Logger.getLogger(Liquidaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        //FIN PRUEBA
        
        //Inicio Llama a Ventana Liquidacion
        Liquidacion liquidacion = new Liquidacion(this.lblTemporada.getText(), Recibidor.getCodigorec(), Recibidor.getNombre(),"",detalle);
        liquidacion.setVisible(true);
        
        liquidacion.lblDesTemporada.setText(this.lblDesTemporada.getText());
        //Fin de la llamada a Ventana Liquidacion
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblLotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLotesMouseClicked
        try {
            cargarLiquidacion(evt);
        } catch (SQLException ex) {
            Logger.getLogger(Liquidaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblLotesMouseClicked
    private void cargarLiquidacion(java.awt.event.MouseEvent evt) throws SQLException{
        int fila = tblLotes.rowAtPoint(evt.getPoint());
        ModeloEncabDetalle med = new ModeloEncabDetalle();
        ArrayList<EntidadDetalleLote> detalle = new ArrayList();
        EntidadRecibidor Recibidor = (EntidadRecibidor) cmbRecibidor.getSelectedItem();
        
        String cadena = tblLotes.getValueAt(fila, 0).toString();
        
        int numEntero = Integer.parseInt(cadena);
        detalle = med.consultarEncabDetalle(lblTemporada.getText(), Recibidor.getCodigorec(),numEntero) ;
        
        
        Liquidacion liquidacion = new Liquidacion(this.lblTemporada.getText(), Recibidor.getCodigorec(), 
                Recibidor.getNombre(),"cargar", detalle);
        liquidacion.setVisible(true);
        
        
        
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<EntidadNave> cmbNave;
    private javax.swing.JComboBox<EntidadOv> cmbOv;
    private javax.swing.JComboBox<EntidadRecibidor> cmbRecibidor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblDesTemporada;
    private javax.swing.JLabel lblGastosrecibidor;
    private javax.swing.JLabel lblNave;
    private javax.swing.JLabel lblNumeroViaje;
    private javax.swing.JLabel lblOv;
    private javax.swing.JLabel lblRecibir;
    private java.awt.Label lblTemporada;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTextField txtViaje;
    // End of variables declaration//GEN-END:variables
}
