/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recibidores;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionBD;

/**
 *
 * @author hgonzalez
 */
public class Lotes extends javax.swing.JFrame {

    String CodigoTemporada;
    int Correlativo;
    int Ov;
    public Lotes(String CodigoTemporada, int Correlativo, int Ov) {
        initComponents();
        
        lblTemporada.setText(CodigoTemporada);
        txtOv.setText(String.valueOf(Ov));
        
        //CARGAR TABLA
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            tblLotes.setModel(modelo);

            ConexionBD cnn = new ConexionBD();
            cnn.conectar();
            ResultSet rs = cnn.consulta("SELECT LGTEST, LGCTEM, LGD4NC, LGASNG, LGNDLT, LGAARE, LGBDGC, LGAACD, LGABCD, "
                    + "LGACCD, LGADCD, LGAAPS, LGAGCD, LGASCD, LGBDCD, LGAICD, LGFYCD, LGAHCD, LGRLCD, LGAECD, LGCCAJ "                    
                    + "FROM UNIDATOS.PPARLOT1 WHERE LGCTEM='"+CodigoTemporada+"' and  LGTDLO='LR' and LGD4NC="+Correlativo+" and LGASNG="+Ov+"");
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Marca Lote");
            modelo.addColumn("Temporada");
            modelo.addColumn("Correaltivo");
            modelo.addColumn("OV");            
            modelo.addColumn("Lote");
            modelo.addColumn("Recibidor");
            modelo.addColumn("Contenedor");            
            modelo.addColumn("Especie");
            modelo.addColumn("Grupo");
            modelo.addColumn("Subgrupo");
            modelo.addColumn("Variedad");
            modelo.addColumn("Peso");
            modelo.addColumn("Dimension");
            modelo.addColumn("Envase");
            modelo.addColumn("Categoria");
            modelo.addColumn("Embalaje");            
            modelo.addColumn("Condicion");
            modelo.addColumn("Etiqueta");
            modelo.addColumn("Tipo Frio");
            modelo.addColumn("Calibre");
            modelo.addColumn("Cajas");          

            //                int[] anchos = {50,200};
            //
            //                for(int x = 0; x < cantidadColumnas; x++)
            //                {
                //                    jtLotes.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
                //                }
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                for(int i = 0; i< cantidadColumnas; i++)
                {
                    if (i==0){
                        filas[i] = Boolean.parseBoolean("false");
                    }else{
                        filas[i] = rs.getObject(i + 1);
                    }
                    if (i>0&&i<5){
                        tblLotes.getColumnModel().getColumn(i).setMaxWidth(0);
                        tblLotes.getColumnModel().getColumn(i).setMinWidth(0);
                        tblLotes.getColumnModel().getColumn(i).setPreferredWidth(0);                        
                    }
                }
                modelo.addRow(filas);
            }
        } catch(SQLException ex){

        }
        //CARGAR TABLA        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblOv = new javax.swing.JLabel();
        txtViaje = new javax.swing.JTextField();
        txtRecibidor = new javax.swing.JTextField();
        txtNave = new javax.swing.JTextField();
        txtOv = new javax.swing.JTextField();
        lblDesTemporada = new javax.swing.JLabel();
        lblTemporada = new javax.swing.JLabel();
        lblRecibir = new javax.swing.JLabel();
        lblNave = new javax.swing.JLabel();
        lblViaje = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        lblResultadoneto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblOv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOv.setText("OV");

        txtViaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtViaje.setEnabled(false);
        txtViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViajeActionPerformed(evt);
            }
        });

        txtRecibidor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRecibidor.setEnabled(false);
        txtRecibidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecibidorActionPerformed(evt);
            }
        });

        txtNave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNave.setEnabled(false);
        txtNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaveActionPerformed(evt);
            }
        });

        txtOv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOv.setEnabled(false);
        txtOv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOvActionPerformed(evt);
            }
        });

        lblDesTemporada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDesTemporada.setText("Temporada");

        lblTemporada.setText("CodigoTemp");
        lblTemporada.setEnabled(false);

        lblRecibir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRecibir.setText("Recibidor");

        lblNave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNave.setText("Nave");

        lblViaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblViaje.setText("Viaje");

        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Lote 1", "Lote 2", "Lote 3", "Lote 4", "Lote 5", "Lote 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18", "Title 19", "Title 20", "Title 21"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLotes);

        btnGuardar.setText("Grabar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        jFormattedTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblResultadoneto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblResultadoneto.setText("Resultado Neto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRecibir)
                                    .addComponent(txtRecibidor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDesTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(txtNave, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNave))))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblViaje)
                                    .addComponent(txtViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOv, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOv))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblResultadoneto)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(759, 759, 759)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTemporada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDesTemporada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecibir)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblOv)
                                .addComponent(lblNave)
                                .addComponent(lblResultadoneto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtRecibidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtOv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblViaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViajeActionPerformed

    private void txtRecibidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecibidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecibidorActionPerformed

    private void txtNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaveActionPerformed

    private void txtOvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOvActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    public javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblDesTemporada;
    private javax.swing.JLabel lblNave;
    private javax.swing.JLabel lblOv;
    private javax.swing.JLabel lblRecibir;
    private javax.swing.JLabel lblResultadoneto;
    public javax.swing.JLabel lblTemporada;
    private javax.swing.JLabel lblViaje;
    private javax.swing.JTable tblLotes;
    public javax.swing.JTextField txtNave;
    public javax.swing.JTextField txtOv;
    public javax.swing.JTextField txtRecibidor;
    public javax.swing.JTextField txtViaje;
    // End of variables declaration//GEN-END:variables
}
